DefaultInstance:
  PasswordComplexityPolicy:
    MinLength: 1
    HasLowercase: false
    HasUppercase: false
    HasNumber: false
    HasSymbol: false
  LoginPolicy:
    AllowRegister: false
    IgnoreUnknownUsernames: true # isn't applied during setup (not implemented)

# TIL arbitrary environment variables can be inserted into the YAML :shrug:
# We're doing that here because the asset storage config uses a weird `mapstructure:",remainder" tag`
# This breaks the hierarchical "just works" config norm for Zitadel env vars
AssetStorage:
  Endpoint: $ZITADEL_ASSETSTORAGE_ENDPOINT
  BucketPrefix: zitadel
  AccessKeyID: $ZITADEL_ASSETSTORAGE_ACCESSKEYID
  SecretAccessKey: $ZITADEL_ASSETSTORAGE_SECRETACCESSKEY
  SSL: true
